---
title: "1LBKA"
author: "Claudia Ki"
date: "11/30/2021"
output: html_document
---
1) Use RManova to look for interactions between diet and lps, time is built it
2) BKA doesn't actually fit the assumptions for an anova so 1) is just to roughly see. Use a GMLM for the actual analysis
3) Break down at specific times

Check for interactions using mixed model anova
```{r}
gi <- read.csv("C:/Users/claud/OneDrive - USU/Desktop/ASU green iguana 2021/greeniguanaAnalysis/modData/BKA1LPSlong.csv")
View(gi)
#install.packages("tidyverse")
#install.packages("rstatix")
#install.packages("ggpubr")
library("rstatix")
library("tidyverse")
library("dplyr")
library("ggpubr")
gi$time <- as.factor(gi$time) #convert to factor for the aov
gi$iguanaID <- as.factor(gi$iguanaID)

```

# Mixed model anova
``` {r}
BKAaov <- anova_test(
  data = gi, dv = bka, wid = iguanaID,
  between = c(diet, lps), within = time
)
get_anova_table(BKAaov)
```
Interaction of diet and LPS, main effect of time and diet. 

pairwise is next step...

