---
title: "Lysis"
author: "Claudia Ki"
date: "1/21/2022"
output: html_document
---
Green iguana analysis report on lysis from both challenges

```{r setup, include=FALSE}
gi <- read.csv("C:/Users/claud/OneDrive - USU/Desktop/ASU green iguana 2021/greeniguanaAnalysis/modData/LysLong.csv")
View(gi) #note that all NA rows were omitted automatically during the transposal
library("rstatix")
library("tidyverse")
library("dplyr")
library("ggpubr")
str(gi)
gi$time <- as.factor(gi$time)
gi$iguanaID <- as.factor(gi$iguanaID)
gi$tx <- as.factor(gi$tx)
gi$diet <- as.factor(gi$diet)
gi$lps <- as.factor(gi$lps)
str(gi)
```
# First LPS Challenge
```{r}
data <- gi %>%
  filter(time %in% c("0423lys", "0428lys", "0430lys", "0504lys", "0511lys","0525lys")) 
data$lys<- sqrt(data$lys) #normalize data
anova_test(
  data = data, dv = lys, wid = iguanaID,
  between = c(diet, lps), within = time
)
data %>%
  pairwise_t_test(
    lys ~ time, paired = FALSE, 
    p.adjust.method = "none"
  )
```
# Second LPS Challenge
```{r}
data2 <- gi %>%
  filter(time %in% c("0525lys","0528lys", "0530lys", "0603lys", "0610lys","0624lys")) 
data2$lys<- sqrt(data2$lys) #normalize data
anova_test(
  data = data2, dv = lys, wid = iguanaID,
  between = c(diet, lps), within = time
)
data2 %>%
  pairwise_t_test(
    lys ~ time, paired = FALSE, 
    p.adjust.method = "none"
  )
```

# Summary of First Challenge
1) Main effect of time, specifically, baseline has a higher lysis score than all other days

# Summary of Second Challenge
1) Main effect of LPS (LPS higher)
2) Main effect of time (refer to table above)