---
title: "True Triglycerides"
author: "Claudia Ki"
date: "2/25/2022"
output: html_document
---
Green iguana analysis report on true triglycerides from both challenges

```{r setup, include=FALSE}
gi <- read.csv("C:/Users/claud/OneDrive - USU/Desktop/ASU green iguana 2021/greeniguanaAnalysis/modData/TrueTriLong.csv")
library("rstatix")
library("tidyverse")
library("dplyr")
library("ggpubr")
str(gi)
gi$time <- as.factor(gi$time)
gi$iguanaID <- as.factor(gi$iguanaID)
gi$tx <- as.factor(gi$tx)
gi$diet <- as.factor(gi$diet)
gi$lps <- as.factor(gi$lps)
str(gi)
data <- gi %>%
  filter(time %in% c("0423trtri","0428trtri", "0430trtri", "0504trtri", "0511trtri","0525trtri")) 
data2 <- gi %>%
  filter(time %in% c("0525trtri","0528trtri", "0530trtri", "0603trtri", "0610trtri","0628trtri")) 

```

First LPS Challenge
```{r}
anova_test(
  data = data, dv = trtri, wid = iguanaID,
  between = c(diet, lps), within = time) 

data %>%
  group_by(diet) %>%
  get_summary_stats(trtri, type = "mean_se")

data %>%
  pairwise_t_test(
    trtri ~ time, paired = FALSE, 
    p.adjust.method = "bonferroni"
  )
```
Second LPS Challenge
```{r}
anova_test(
  data = data2, dv = trtri, wid = iguanaID,
  between = c(diet, lps), within = time) 

data2 %>%
  group_by(diet) %>%
  get_summary_stats(trtri, type = "mean_se")

data2 %>%
  pairwise_t_test(
    trtri ~ time, paired = FALSE, 
    p.adjust.method = "bonferroni"
  )
```
# Summary of First Challenge
1) Main Effect of Glucose (glucose higher)
2) Main Effect of Time 
    a) 0423 and 0511 
    b) 0428 and 0511

# Summary of Second Challenge
1) Main Effect of Glucose (glucose higher)
2) Main Effect of Time
    a) 0603 (1wk)and 0525(pre), 0528(24h), 0530(72h)
    b) 0610 (2wk)and 0525(pre), 0528(24h), 0530(72h)
    c) 0528 (24hr)and 0628(4wk)
