---
title: "Glucose"
author: "Claudia Ki"
date: "3/1/2022"
output: html_document
---
Green iguana analysis report on glucose from both challenges

```{r setup, include=FALSE}
gi <- read.csv("C:/Users/claud/OneDrive - USU/Desktop/ASU green iguana 2021/greeniguanaAnalysis/modData/GlucoseLong.csv")

library("rstatix")
library("tidyverse")
library("dplyr")
library("ggpubr")
str(gi)
gi$time <- as.factor(gi$time)
gi$iguanaID <- as.factor(gi$iguanaID)
gi$tx <- as.factor(gi$tx)
gi$diet <- as.factor(gi$diet)
gi$lps <- as.factor(gi$lps)
str(gi)

data <- gi %>%
  filter(time %in% c("0423glu","0430glu", "0428glu", "0525glu")) 
data2 <- gi %>%
  filter(time %in% c("0528glu","0530glu", "0624glu", "0525glu"))  
```

Primary LPS Challenge
```{r}
anova_test(
  data = data, dv = glu, wid = iguanaID,
  between = c(diet, lps), within = time) 

data %>%
  pairwise_t_test(
    glu ~ time, paired = FALSE, 
    p.adjust.method = "bonferroni"
  )
```

Secondary LPS Challenge
```{r}
anova_test(
  data = data2, dv = glu, wid = iguanaID,
  between = c(diet, lps), within = time) 
```

# Summary of Primary Challenge
1) Main effect of time (0423 and 0430)

# Sumary of Secondary Challenge
1) No effect