---
title: "OXY"
author: "Claudia Ki"
date: "1/25/2022"
output: html_document
---
Green Iguana analysis over course of both challenge

```{r setup, include=FALSE}
gi <- read.csv("C:/Users/claud/OneDrive - USU/Desktop/ASU green iguana 2021/greeniguanaAnalysis/modData/OXYlong.csv")
View(gi) #note that all NA rows were omitted automatically during the transposal
library("rstatix")
library("tidyverse")
library("dplyr")
library("ggpubr")
str(gi)
gi$time <- as.factor(gi$time)
gi$iguanaID <- as.factor(gi$iguanaID)
gi$tx <- as.factor(gi$tx)
gi$diet <- as.factor(gi$diet)
gi$lps <- as.factor(gi$lps)
str(gi)
```
First LPS challenge
```{r}
data <- gi %>%
  filter(time %in% c("0423oxystd","0428oxystd", "0430oxystd", "0504oxystd", "0511oxystd","0525oxystd")) 
anova_test(
  data = data, dv = oxy, wid = iguanaID,
  between = c(diet, lps), within = time) 
```
Secondary LPS Challenge
```{r}
data <- gi %>%
  filter(time %in% c("0525oxystd","0528oxystd", "0530oxystd", "0603oxystd", "0610oxystd","0624oxystd")) 
anova_test(
  data = data, dv = oxy, wid = iguanaID,
  between = c(diet, lps), within = time) 
```
# Summary of First Challenge
1) No effect

# Summary of Second Challenge
1) No effect
